import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'hi' | 'kn';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    'app.name': 'WhereIsMyBus',
    'nav.home': 'Home',
    'nav.favorites': 'Favorites',
    'nav.settings': 'Settings',
    'nav.alerts': 'Alerts',
    'search.placeholder': 'Where do you want to go?',
    'search.from': 'From',
    'search.to': 'To',
    'search.button': 'Search Buses',
    'search.track_your_bus': 'Track Your Bus',
    'search.bus_number': 'Bus Number',
    'search.bus_number_placeholder': 'Enter bus number (e.g., 335E, BM5)',
    'search.or': 'OR',
    'search.from_placeholder': 'Starting point',
    'search.to_placeholder': 'Destination',
    'smart.features': 'SMART FEATURES',
    'smart.featured': 'Featured',
    'smart.new': 'NEW',
    'nav.menu': 'Menu',
    'nav.welcome': 'Welcome',
    'nav.traveler': 'Bus Traveler',
    'nav.all_routes': 'All Routes',
    'nearby.stops': 'Nearby Stops',
    'recent.searches': 'Recent Searches',
    'bus.buddy': 'Bus Buddy AI',
    'seat.vacancy': 'Seat Vacancy',
    'weather.routes': 'Weather Aware',
    'crowd.prediction': 'Crowd Prediction',
    'favorites.saved_routes': 'saved routes',
    'favorites.track_now': 'Track Now',
    'favorites.no_favorites': 'No Favorites Yet',
    'favorites.no_favorites_desc': 'Start adding your frequently used routes to access them quickly',
    'favorites.explore_routes': 'Explore Routes',
    'favorites.every': 'Every',
    'crowd.level.high': 'High',
    'crowd.level.medium': 'Medium',
    'crowd.level.low': 'Low',
    'time.now': 'Now',
    'time.30min': '30 min',
    'time.1hr': '1 hour',
    'time.2hr': '2 hours',
    'crowd.stats.low': 'Low Crowd',
    'crowd.stats.medium': 'Medium',
    'crowd.stats.high': 'High Crowd',
    'crowd.live_predictions': 'LIVE PREDICTIONS',
    'crowd.current_level': 'Current Crowd Level',
    'crowd.peak_time': 'Peak Time',
    'crowd.view_history': 'View History',
    'crowd.track_bus': 'Track Bus',
    'crowd.how_it_works': 'HOW IT WORKS',
    'crowd.ai_analysis': 'AI-Powered Analysis',
    'crowd.ai_desc': 'Our AI analyzes historical data, time of day, and current occupancy to predict crowd levels',
    'crowd.real_time': 'Real-time Updates',
    'crowd.real_time_desc': 'Predictions are updated every minute based on live bus occupancy data',
    'crowd.smart_recs': 'Smart Recommendations',
    'crowd.smart_recs_desc': 'Get personalized suggestions for the best time to travel and alternative routes',
    'settings.preferences': 'PREFERENCES',
    'settings.notifications': 'Notifications',
    'settings.location': 'Location Access',
    'settings.darkMode': 'Dark Mode',
    'settings.general': 'GENERAL',
    'settings.language': 'Language',
    'settings.about': 'About',
    'settings.version': 'Version',
    'language.select': 'Select Language',
    'language.en': 'English',
    'language.hi': 'Hindi',
    'language.kn': 'Kannada',
    'live.tracking': 'Live Tracking',
    'bus.n': 'Bus',
    'current.location': 'Current Location',
    'view.on.map': 'View on Map',
    'route.timeline': 'Route Timeline',
    'view.all.stops': 'View All Stops',
    'status.on_time': 'On Time',
    'status.eta': 'ETA',
    'status.speed': 'Speed',
    'status.arriving': 'Arriving',
    'status.passed': 'Passed',
    'bus.approaching': 'Bus is approaching this stop',
    'alert.set': 'Set Arrival Alert',
    'route.label': 'Route',
    'view.directions': 'View directions in Google Maps',
    'view.all.routes': 'View All Routes',
    'about.app_name': 'WhereIsMyBus',
    'about.track_realtime': 'Track your bus in real-time',
    'about.desc': 'WhereIsMyBus is your ultimate companion for tracking buses in Indian cities. Get real-time updates on BMTC, KSRTC, and APSRTC buses, check seat availability, and plan your journey with AI-powered suggestions.',
    'about.key_features': 'KEY FEATURES',
    'about.feature.tracking': 'Real-time Bus Tracking',
    'about.feature.tracking_desc': 'Track your bus location live on map',
    'about.feature.ai': 'AI-Powered Suggestions',
    'about.feature.ai_desc': 'Get smart route recommendations',
    'about.feature.seats': 'Seat Availability',
    'about.feature.seats_desc': 'Check vacant seats before boarding',
    'about.feature.weather': 'Weather-Aware Routes',
    'about.feature.weather_desc': 'Plan routes based on weather conditions',
    'about.contact': 'CONTACT & SUPPORT',
    'about.privacy': 'Privacy Policy',
    'about.terms': 'Terms of Service',
    'about.made_with': 'Made with',
    'about.in_india': 'in India',
    'about.rights': 'All rights reserved.',
  },
  hi: {
    'app.name': 'मेरी बस कहाँ है',
    'nav.home': 'होम',
    'nav.favorites': 'पसंदीदा',
    'nav.settings': 'सेटिंग्स',
    'nav.alerts': 'अलर्ट',
    'search.placeholder': 'आप कहाँ जाना चाहते हैं?',
    'search.from': 'कहाँ से',
    'search.to': 'कहाँ तक',
    'search.button': 'बसें खोजें',
    'search.track_your_bus': 'अपनी बस ट्रैक करें',
    'search.bus_number': 'बस नंबर',
    'search.bus_number_placeholder': 'बस नंबर दर्ज करें (जैसे, 335E, BM5)',
    'search.or': 'या',
    'search.from_placeholder': 'शुरुआती बिंदु',
    'search.to_placeholder': 'गंतव्य',
    'smart.features': 'स्मार्ट फीचर्स',
    'smart.featured': 'फ़ीचर्ड',
    'smart.new': 'नया',
    'nav.menu': 'मेनू',
    'nav.welcome': 'स्वागत हे',
    'nav.traveler': 'बस यात्री',
    'nav.all_routes': 'सभी मार्ग',
    'nearby.stops': 'निकटतम स्टॉप',
    'recent.searches': 'हाल ही की खोजें',
    'bus.buddy': 'बस बडी AI',
    'seat.vacancy': 'सीट खाली',
    'weather.routes': 'मौसम मार्ग',
    'crowd.prediction': 'भीड़ पूर्वानुमान',
    'favorites.saved_routes': 'सहेजे गए मार्ग',
    'favorites.track_now': 'अभी ट्रैक करें',
    'favorites.no_favorites': 'अभी तक कोई पसंदीदा नहीं',
    'favorites.no_favorites_desc': 'उन्हें जल्दी से एक्सेस करने के लिए अपने अक्सर उपयोग किए जाने वाले मार्गों को जोड़ना शुरू करें',
    'favorites.explore_routes': 'मार्ग खोजें',
    'favorites.every': 'हर',
    'crowd.level.high': 'उच्च',
    'crowd.level.medium': 'मध्यम',
    'crowd.level.low': 'कम',
    'time.now': 'अभी',
    'time.30min': '30 मिनट',
    'time.1hr': '1 घंटा',
    'time.2hr': '2 घंटे',
    'crowd.stats.low': 'कम भीड़',
    'crowd.stats.medium': 'मध्यम',
    'crowd.stats.high': 'ज्यादा भीड़',
    'crowd.live_predictions': 'लाइव भविष्यवाणियां',
    'crowd.current_level': 'वर्तमान भीड़ स्तर',
    'crowd.peak_time': 'पीक टाइम',
    'crowd.view_history': 'इतिहास देखें',
    'crowd.track_bus': 'बस ट्रैक करें',
    'crowd.how_it_works': 'यह कैसे काम करता है',
    'crowd.ai_analysis': 'AI-संचालित विश्लेषण',
    'crowd.ai_desc': 'हमारा AI भीड़ के स्तर का अनुमान लगाने के लिए ऐतिहासिक डेटा, दिन के समय और वर्तमान अधिभोग का विश्लेषण करता है',
    'crowd.real_time': 'वास्तविक समय अपडेट',
    'crowd.real_time_desc': 'लाइव बस अधिभोग डेटा के आधार पर हर मिनट भविष्यवाणियां अपडेट की जाती हैं',
    'crowd.smart_recs': 'स्मार्ट सिफारिशें',
    'crowd.smart_recs_desc': 'यात्रा के लिए सबसे अच्छा समय और वैकल्पिक मार्गों के लिए व्यक्तिगत सुझाव प्राप्त करें',
    'settings.preferences': 'प्राथमिकताएं',
    'settings.notifications': 'सूचनाएं',
    'settings.location': 'स्थान का उपयोग',
    'settings.darkMode': 'डार्क मोड',
    'settings.general': 'सामान्य',
    'settings.language': 'भाषा',
    'settings.about': 'के बारे में',
    'settings.version': 'संस्करण',
    'language.select': 'भाषा चुनें',
    'language.en': 'अंग्रेज़ी',
    'language.hi': 'हिंदी',
    'language.kn': 'कन्नड़',
    'live.tracking': 'लाइव ट्रैकिंग',
    'bus.n': 'बस',
    'current.location': 'वर्तमान स्थान',
    'view.on.map': 'मानचित्र पर देखें',
    'route.timeline': 'रूट टाइमलाइन',
    'view.all.stops': 'सभी स्टॉप देखें',
    'status.on_time': 'समय पर',
    'status.eta': 'आगमन',
    'status.speed': 'गति',
    'status.arriving': 'पहुँच रही है',
    'status.passed': 'गुजर चुकी',
    'bus.approaching': 'बस इस स्टॉप पर आ रही है',
    'alert.set': 'आगमन अलर्ट सेट करें',
    'route.label': 'मार���ग',
    'view.directions': 'Google मैप्स में दिशा-निर्देश देखें',
    'view.all.routes': 'सभी मार्ग देखें',
    'about.app_name': 'मेरी बस कहाँ है',
    'about.track_realtime': 'अपनी बस को रियल-टाइम में ट्रैक करें',
    'about.desc': 'WhereIsMyBus भारतीय शहरों में बसों को ट्रैक करने के लिए आपका अंतिम साथी है। BMTC, KSRTC और APSRTC बसों पर वास्तविक समय अपडेट प्राप्त करें, सीट की उपलब्धता की जांच करें, और AI-संचालित सुझावों के साथ अपनी यात्रा की योजना बनाएं।',
    'about.key_features': 'प्रमुख विशेषताऐं',
    'about.feature.tracking': 'रियल-टाइम बस ट्रैकिंग',
    'about.feature.tracking_desc': 'मानचित्र पर अपनी बस का स्थान लाइव ट्रैक करें',
    'about.feature.ai': 'AI-संचालित सुझाव',
    'about.feature.ai_desc': 'स्मार्ट रूट सिफारिशें प्र���प्त करें',
    'about.feature.seats': 'सीट उपलब्धता',
    'about.feature.seats_desc': 'बोर्डिंग से पहले खाली सीटों की जांच करें',
    'about.feature.weather': 'मौसम-जागरूक मार्ग',
    'about.feature.weather_desc': 'मौसम की स्थिति के आधार पर मार्गों की योजना बनाएं',
    'about.contact': 'संपर्क और सहायता',
    'about.privacy': 'गोपनीयता नीति',
    'about.terms': 'सेवा की शर्तें',
    'about.made_with': 'भारत में',
    'about.in_india': 'के साथ बनाया गया',
    'about.rights': 'सर्वाधिकार सुरक्षित।',
  },
  kn: {
    'app.name': 'ನನ್ನ ಬಸ್ ಎಲ್ಲಿದೆ',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.favorites': 'ಮೆಚ್ಚಿನವುಗಳು',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.alerts': 'ಎಚ್ಚರಿಕೆಗಳು',
    'search.placeholder': 'ನೀವು ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು?',
    'search.from': 'ಇಂದ',
    'search.to': 'ಗೆ',
    'search.button': 'ಬಸ್‌ಗಳನ್ನು ಹುಡುಕಿ',
    'search.track_your_bus': 'ನಿಮ್ಮ ಬಸ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'search.bus_number': 'ಬಸ್ ಸಂಖ್ಯೆ',
    'search.bus_number_placeholder': 'ಬಸ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ (ಉದಾ, 335E, BM5)',
    'search.or': 'ಅಥವಾ',
    'search.from_placeholder': 'ಪ್ರಾರಂಭದ ಸ್ಥಳ',
    'search.to_placeholder': 'ಗಮ್ಯಸ್ಥಾನ',
    'smart.features': 'ಸ್ಮಾರ್ಟ್ ವೈಶಿಷ್ಟ್ಯಗಳು',
    'smart.featured': 'ವೈಶಿಷ್ಟ್ಯಗೊಳಿಸಿದ',
    'smart.new': 'ಹೊಸ',
    'nav.menu': 'ಮೆನು',
    'nav.welcome': 'ಸ್ವಾಗತ',
    'nav.traveler': 'ಬಸ್ ಪ್ರಯಾಣಿಕ',
    'nav.all_routes': 'ಎಲ್ಲಾ ಮಾರ್ಗಗಳು',
    'nearby.stops': 'ಹತ್ತಿರದ ನಿಲ್ದಾಣಗಳು',
    'recent.searches': 'ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು',
    'bus.buddy': 'ಬಸ್ ಬಡಿ AI',
    'seat.vacancy': 'ಸೀಟ್ ಖಾಲಿ',
    'weather.routes': 'ಹವಾಮಾನ ಮಾರ್ಗಗಳು',
    'crowd.prediction': 'ಜನಸಂದಣಿ ಮುನ್ಸೂಚನೆ',
    'favorites.saved_routes': 'ಉಳಿಸಿದ ಮಾರ್ಗಗಳು',
    'favorites.track_now': 'ಈಗ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'favorites.no_favorites': 'ಇನ್ನೂ ಯಾವುದೇ ಮೆಚ್ಚಿನವುಗಳಿಲ್ಲ',
    'favorites.no_favorites_desc': 'ಅವುಗಳನ್ನು ತ್ವರಿತವಾಗಿ ಪ್ರವೇಶಿಸಲು ನಿಮ್ಮ ಆಗಾಗ್ಗೆ ಬಳಸುವ ಮಾರ್ಗಗಳನ್ನು ಸೇರಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
    'favorites.explore_routes': 'ಮಾರ್ಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    'favorites.every': 'ಪ್ರತಿ',
    'crowd.level.high': 'ಹೆಚ್ಚು',
    'crowd.level.medium': 'ಮಧ್ಯಮ',
    'crowd.level.low': 'ಕಡಿಮೆ',
    'time.now': 'ಈಗ',
    'time.30min': '30 ನಿಮಿಷ',
    'time.1hr': '1 ಗಂಟೆ',
    'time.2hr': '2 ಗಂಟೆಗಳು',
    'crowd.stats.low': 'ಕಡಿಮೆ ಜನಸಂದಣಿ',
    'crowd.stats.medium': 'ಮಧ್ಯಮ',
    'crowd.stats.high': 'ಹೆಚ್ಚು ಜನಸಂದಣಿ',
    'crowd.live_predictions': 'ಲೈವ್ ಮುನ್ನೋಟಗಳು',
    'crowd.current_level': 'ಪ್ರಸ್ತುತ ಜನಸಂದಣಿ ಮಟ್ಟ',
    'crowd.peak_time': 'ಪೀಕ್ ಸಮಯ',
    'crowd.view_history': 'ಇತಿಹಾಸ ವೀಕ್ಷಿಸಿ',
    'crowd.track_bus': 'ಬಸ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'crowd.how_it_works': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    'crowd.ai_analysis': 'AI-ಚಾಲಿತ ವಿಶ್ಲೇಷಣೆ',
    'crowd.ai_desc': 'ಜನಸಂದಣಿ ಮಟ್ಟವನ್ನು ಊಹಿಸಲು ನಮ್ಮ AI ಐತಿಹಾಸಿಕ ಡೇಟಾ, ದಿನದ ಸಮಯ ಮತ್ತು ಪ್ರಸ್ತುತ ಆಕ್ಯುಪೆನ್ಸಿಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ',
    'crowd.real_time': 'ನೈಜ-ಸಮಯದ ನವೀಕರಣಗಳು',
    'crowd.real_time_desc': 'ಲೈವ್ ಬಸ್ ಆಕ್ಯುಪೆನ್ಸಿ ಡೇಟಾವನ್ನು ಆಧರಿಸಿ ಪ್ರತಿ ನಿಮಿಷಕ್ಕೆ ಮುನ್ನೋಟಗಳನ್ನು ನವೀಕರಿಸಲಾಗುತ್ತದೆ',
    'crowd.smart_recs': 'ಸ್ಮಾರ್ಟ್ ಶಿಫಾರಸುಗಳು',
    'crowd.smart_recs_desc': 'ಪ್ರಯಾಣಿಸಲು ಉತ್ತಮ ಸಮಯ ಮತ್ತು ಪರ್ಯಾಯ ಮಾರ್ಗಗಳಿಗಾಗಿ ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ',
    'settings.preferences': 'ಆದ್ಯತೆಗಳು',
    'settings.notifications': 'ಸೂಚನೆಗಳು',
    'settings.location': 'ಸ್ಥಳ ಪ್ರವೇಶ',
    'settings.darkMode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'settings.general': 'ಸಾಮಾನ್ಯ',
    'settings.language': 'ಭಾಷೆ',
    'settings.about': 'ಕುರಿತು',
    'settings.version': 'ಆವೃತ್ತಿ',
    'language.select': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'language.en': 'ಇಂಗ್ಲಿಷ್',
    'language.hi': 'ಹಿಂದಿ',
    'language.kn': 'ಕನ್ನಡ',
    'live.tracking': 'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    'bus.n': 'ಬಸ್',
    'current.location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
    'view.on.map': 'ನಕ್ಷೆಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
    'route.timeline': 'ಮಾರ್ಗ ಟೈಮ್‌ಲೈನ್',
    'view.all.stops': 'ಎಲ್ಲಾ ನಿಲ್ದಾಣಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'status.on_time': 'ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ',
    'status.eta': 'ನಿರೀಕ್ಷಿತ ಸಮಯ',
    'status.speed': 'ವೇಗ',
    'status.arriving': 'ತಲುಪುತ್ತಿದೆ',
    'status.passed': 'ಹಾದುಹೋಗಿದೆ',
    'bus.approaching': 'ಬಸ್ ಈ ನಿಲ್ದಾಣವನ್ನು ಸಮೀಪಿಸುತ್ತಿದೆ',
    'alert.set': 'ಆಗಮನ ಎಚ್ಚರಿಕೆಯನ್ನು ಹೊಂದಿಸಿ',
    'route.label': 'ಮಾರ್ಗ',
    'view.directions': 'Google ನಕ್ಷೆಗಳಲ್ಲಿ ದಿಕ್ಕುಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'view.all.routes': 'ಎಲ್ಲಾ ಮಾರ್ಗಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'about.app_name': 'ನನ್ನ ಬಸ್ ಎಲ್ಲಿದೆ',
    'about.track_realtime': 'ನಿಮ್ಮ ಬಸ್ ಅನ್ನು ರಿಯಲ್-ಟೈಮ್‌ನಲ್ಲಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'about.desc': 'WhereIsMyBus ಭಾರತೀಯ ನಗರಗಳಲ್ಲಿ ಬಸ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಅಂತಿಮ ಒಡನಾಡಿಯಾಗಿದೆ. BMTC, KSRTC ಮತ್ತು APSRTC ಬಸ್‌ಗಳ ನೈಜ-ಸಮಯದ ನವೀಕರಣಗಳನ್ನು ಪಡೆಯಿರಿ, ಆಸನ ಲಭ್ಯತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು AI-ಚಾಲಿತ ಸಲಹೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಯೋಜಿಸಿ.',
    'about.key_features': 'ಪ್ರಮುಖ ಲಕ್ಷಣಗಳು',
    'about.feature.tracking': 'ರಿಯಲ್-ಟೈಮ್ ಬಸ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    'about.feature.tracking_desc': 'ನಕ್ಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಬಸ್ ಸ್ಥಳವನ್ನು ಲೈವ್ ಆಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'about.feature.ai': 'AI-ಚಾಲಿತ ಸಲಹೆಗಳು',
    'about.feature.ai_desc': 'ಸ್ಮಾರ್ಟ್ ಮಾರ್ಗ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
    'about.feature.seats': 'ಆಸನ ಲಭ್ಯತೆ',
    'about.feature.seats_desc': 'ಹತ್ತುವ ಮೊದಲು ಖಾಲಿ ಆಸನಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    'about.feature.weather': 'ಹವಾಮಾನ ಅರಿವು ಮಾರ್ಗಗಳು',
    'about.feature.weather_desc': 'ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿಗಳ ಆಧಾರದ ಮೇಲೆ ಮಾರ್ಗಗಳನ್ನು ಯೋಜಿಸಿ',
    'about.contact': 'ಸಂಪರ್ಕ ಮತ್ತು ಬೆಂಬಲ',
    'about.privacy': 'ಗೌಪ್ಯತೆ ನೀತಿ',
    'about.terms': 'ಸೇವಾ ನಿಯಮಗಳು',
    'about.made_with': 'ಭಾರತದಲ್ಲಿ',
    'about.in_india': 'ನೊಂದಿಗೆ ಮಾಡಲಾಗಿದೆ',
    'about.rights': 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
